### PR TITLE
Add EXIT handler for cleanup. Fix #49.

### LINKED ISSUE #49: Cleanup after yourself even if everthing.sh fails
Currently, we only clean up  after a successful run... I think we want to do an `--unsafe` cleanup regardless?

### PR DESCRIPTION
**Pull request by mccalluc**
@afred?

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc given that `destroy.sh --unsafe` is analogous to `rm -rf` for AWS resources, would it be a good idea to add additional sanity checking around the `$NAME` param? I.e. match it against `^\d+\.wgbh\-mla\-test\.org$` or something?

**Comment by mccalluc** [comment]
At the very least, I'll add a check like that to everything.sh... More generally, I'm not sure. In this phase, I feel like I'm more likely to delete the wrong thing accidentally through the UI than the command line... but in maintenance mode that might not be true?

**Comment by afred** [comment]
@mccalluc no idea why that's not passing. Travis using a different `grep`?

**Comment by mccalluc** [comment]
@afred: so this will prevent you from shooting yourself in the foot with `everything.sh`.

As for `destroy.sh`, would another level of confirmation do it for you? Or do you really want it to work only for numbered, ie travis, instances?

**Comment by afred** [comment]
@mccalluc I think this is a good enogh, keeping in mind that we should implement likewise checks _any_ time we invoke `destroy.rb` indirectly,

**Pull request merged**
