### PR TITLE
Aws wrap less

### PR DESCRIPTION
**Pull request by mccalluc**
Remove a lot of code because we decided we are not interested in rsyncing ebs vollumes.

### CODE REVIEW

**Comment by mccalluc** [comment]
(Don't really understand the failure... but given the overlap between this PR and the other one, it might make more sense to get that one in, then rebase this on top of that, and then take it from there.)

**Comment by afred** [comment]
@mccalluc I'm having 2nd thoughts about removing this entirely because I think we'll want to look closer at detachable volumes for HydraDAM, and possibly for AAPB as we bring in more content.

Would you feel more comfortable leaving this code in, but "turning it off" for OV and AAPB?

Or would you rather actually remove it, and wait for a real use case to add it back in?

I have a weak preference for the former.

**Comment by mccalluc** [comment]
I don't have strong feelings here: there are good arguments either way.

**Comment by mccalluc** [comment]
Decided that swap and rsync should be separate, but we still want rsync.

**Pull request closed without merging**
