### PR TITLE
Dumb mistake.

### PR DESCRIPTION
**Pull request by mccalluc**
Failure is another ssh connection problem like we've been seeing recently. I'll put a retry loop around that and see if it helps? Maybe something should be synchronous which is currently asynchronous...

### CODE REVIEW

**Comment by mccalluc** [comment]
It doesn't look like it is actually retrying: https://travis-ci.org/WGBH/aws-wrapper/builds/138946580#L415
```
WARN [2016-06-20 16:09:05]: (But new servers need time to warm up. Will retry.)
INFO [2016-06-20 16:09:05]: Updated one-205.wgbh-mla-test.org (184.73.24.131) via SSH.
```
Something should come between these lines?

**Comment by mccalluc** [comment]
Moving in the right direction: Now explicitly waiting after instance state change. Need to fix rspec tests...

**Comment by mccalluc** [comment]
@Muraszko ? I had thought I was testing stop and start in everything.sh, but I simply wasn't. When I fixed the coverage, many other errors become apparent.

**Comment by Muraszko** [comment]
@mccalluc Tested stop and start on demo.bostonlocal seems to work well!

**Pull request merged**
